[Main]
# Default catalog. If empty, last catalog used will be open by LrViewer
LRCatalog =

# Date format DD/MM/YY if True else YY/MM/DD
DayFirst = False

# File system encoding
FSEncoding = cp1252

# GeoCoder service (BanFrance or Nominatim)
GeoCoder = Nominatim



